description: 
pack: aws
enabled: true
entry_point: run.py
name: sns_list_platform_applications
runner_type: run-python
parameters:
  action:
    default: list_platform_applications
    immutable: true
    type: string
  cls:
    default: sns
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  NextToken:
    type: string
    description: ""