description: 
pack: aws
enabled: true
entry_point: run.py
name: sns_create_platform_application
runner_type: run-python
parameters:
  action:
    default: create_platform_application
    immutable: true
    type: string
  cls:
    default: sns
    type: string
  headers:
    type: string
  module_path:
    default: boto3
    immutable: true
    type: string
  Name:
    type: string
    description: ""
    required: true
  Platform:
    type: string
    description: ""
    required: true
  Attributes:
    type: map
    description: ""
    required: true